version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 864899837235.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t aws-assessment-basim .
      - docker tag aws-assessment-basim:latest 864899837235.dkr.ecr.ap-south-1.amazonaws.com/user26/basim-repo:latest

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 864899837235.dkr.ecr.ap-south-1.amazonaws.com/user26/basim-repo:latest
      - echo Writing image definitions file...
      - printf '[{"name":"aws-assessment-basim-container","imageUri":"%s"}]' 864899837235.dkr.ecr.ap-south-1.amazonaws.com/user26/basim-repo:latest > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
